{'algebra': 'Extended_Linear_Interval_Algebra',
 'description': 'Using Semantic Web Technology to Exploit Soft Information',
 'edges': [['Yesterday', 'Today', 'M'],
           ['Yesterday', 'Yesterday_Morning', 'SI'],
           ['Yesterday', 'Yesterday_Evening', 'FI'],
           ['Today', 'Time_of_Release', 'DI'],
           ['Yesterday_Morning', 'Yesterday_Evening', 'B'],
           ['Yesterday_Morning', 'Time_of_Arrest', 'DI'],
           ['Yesterday_Evening', 'Time_of_Obs', 'DI'],
           ['Time_of_Arrest', 'Period_of_Detention', 'PS'],
           ['Time_of_Release', 'Period_of_Detention', 'PF']],
 'name': 'NSSDF 2009 Example 2',
 'nodes': [['Yesterday', ['ProperInterval']],
           ['Today', ['ProperInterval']],
           ['Yesterday_Morning', ['ProperInterval']],
           ['Yesterday_Evening', ['ProperInterval']],
           ['Time_of_Obs', ['Point']],
           ['Time_of_Arrest', ['Point']],
           ['Time_of_Release', ['Point']],
           ['Period_of_Detention', ['ProperInterval', 'Point']]]}
